import type {Metadata} from "next";

import Link from "next/link";
import {Inter} from "next/font/google";

import "./globals.css";
const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Juan Ruocco Quotes Generator",
  description: "Generated by pnvdev",
};

export default async function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body
        className={`container m-auto grid min-h-screen grid-rows-[auto,1fr,auto] gap-8 bg-background px-4 font-sans antialiased ${inter.className}`}
      >
        <header className="font-mono text-xl font-bold leading-[4rem]">
          <Link href="/">Juan Ruocco Quotes Generator</Link>
        </header>
        {children}
      </body>
    </html>
  );
}
